name: Build Auriel AI APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android/src
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Auriel-AI-debug
          path: Android/src/app/build/outputs/apk/debug/*.apk
